2022-03-24 00:36:37,077 INFO    MainThread:29632 [wandb_setup.py:_flush():75] Loading settings from C:\Users\anshu\.config\wandb\settings
2022-03-24 00:36:37,078 INFO    MainThread:29632 [wandb_setup.py:_flush():75] Loading settings from C:\Users\anshu\OneDrive\Desktop\munnu\MIRNet\wandb\settings
2022-03-24 00:36:37,078 INFO    MainThread:29632 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2022-03-24 00:36:37,078 INFO    MainThread:29632 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program': 'C:\\Users\\anshu\\OneDrive\\Desktop\\munnu\\MIRNet\\main.py'}
2022-03-24 00:36:37,079 INFO    MainThread:29632 [wandb_init.py:_log_setup():405] Logging user logs to C:\Users\anshu\OneDrive\Desktop\munnu\MIRNet\wandb\run-20220324_003637-4lzy5shk\logs\debug.log
2022-03-24 00:36:37,088 INFO    MainThread:29632 [wandb_init.py:_log_setup():406] Logging internal logs to C:\Users\anshu\OneDrive\Desktop\munnu\MIRNet\wandb\run-20220324_003637-4lzy5shk\logs\debug-internal.log
2022-03-24 00:36:37,088 INFO    MainThread:29632 [wandb_init.py:init():439] calling init triggers
2022-03-24 00:36:37,089 INFO    MainThread:29632 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-03-24 00:36:37,089 INFO    MainThread:29632 [wandb_init.py:init():492] starting backend
2022-03-24 00:36:37,089 INFO    MainThread:29632 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-03-24 00:36:37,105 INFO    MainThread:29632 [backend.py:ensure_launched():219] starting backend process...
2022-03-24 00:36:37,232 INFO    MainThread:29632 [backend.py:ensure_launched():224] started backend process with pid: 24960
2022-03-24 00:36:37,232 INFO    MainThread:29632 [wandb_init.py:init():501] backend started and connected
2022-03-24 00:36:37,234 INFO    MainThread:29632 [wandb_init.py:init():565] updated telemetry
2022-03-24 00:36:37,327 INFO    MainThread:29632 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-24 00:37:07,337 INFO    MainThread:29632 [interface_shared.py:_communicate_run():322] couldn't get run from backend
2022-03-24 00:37:07,337 ERROR   MainThread:29632 [wandb_init.py:init():601] backend process timed out
2022-03-24 00:37:07,337 ERROR   MainThread:29632 [wandb_init.py:init():610] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-03-24 00:37:07,363 ERROR   MainThread:29632 [wandb_init.py:init():981] error
Traceback (most recent call last):
  File "C:\Users\anshu\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\wandb_init.py", line 954, in init
    run = wi.init()
  File "C:\Users\anshu\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\wandb_init.py", line 614, in init
    backend.cleanup()
  File "C:\Users\anshu\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\backend\backend.py", line 248, in cleanup
    self.interface.join()
  File "C:\Users\anshu\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\interface\interface_shared.py", line 467, in join
    super().join()
  File "C:\Users\anshu\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\interface\interface.py", line 630, in join
    _ = self._communicate_shutdown()
  File "C:\Users\anshu\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\interface\interface_shared.py", line 464, in _communicate_shutdown
    _ = self._communicate(record)
  File "C:\Users\anshu\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\interface\interface_shared.py", line 222, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\anshu\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\interface\interface_shared.py", line 227, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
